name = "medicare-frontend"
account_id = "1916833baf2f14150a64c373a066f53f" # Your Cloudflare account ID
workers_dev = true
compatibility_date = "2023-01-01"

[site]
bucket = "./build"
entry-point = "."

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
name = "medicare-frontend-production"

[env.staging]
name = "medicare-frontend-staging" 