name = "medicare-api"
type = "webpack"
account_id = "" # Your Cloudflare account ID
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-01-01"

[build]
command = "npm install"

[env.production]
name = "medicare-api-production"

[env.staging]
name = "medicare-api-staging"

[[kv_namespaces]]
binding = "MEDICARE_KV"
id = "" # Your KV namespace ID 